version: '3.5'
services:
  frontend:
      image: ml-front
      ports:
        - 3000:3000
      depends_on:
        - backend
  backend:
      image: ml-back
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
      depends_on:
        - training
  training:
      image: ml-training
      volumes:
        - model:/src/model
        - imgs:/src/imgs
volumes:
  imgs:
  model: