version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=amadeus
      - POSTGRES_PASSWORD=pass
  backend:
    image: back
    environment:
      - DB_USERNAME=amadeus
      - DB_PASSWORD=pass
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
      image: front
      ports:
        - 5000:5000