version: '3.5'

services:
  redis:
    image: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=amadeus
      - POSTGRES_PASSWORD=pass
  backend:
    image: back
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=amadeus
      - DB_PASSWORD=pass
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
      image: front
      ports:
        - 5000:5000